name: Publish NuGet packages

on:
  release:
    types: [published]

env:
  ARTIFACTS_FEED_URL: https://api.nuget.org/v3/index.json
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "8.x"
  PACKABLE_PROJECTS: "Neolution.Utilities,Neolution.Utilities.AspNetCore,Neolution.Utilities.EntityFrameworkCore"

jobs:
  build-pack-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY_NEOLUTION }}

      - name: Determine version for NuGet package
        run: echo "NUGET_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore, build, and pack all projects
        run: |
          IFS=',' read -ra PROJECTS <<< "$PACKABLE_PROJECTS"
          for proj in "${PROJECTS[@]}"; do
            proj_path="$proj/$proj.csproj"
            echo "Processing $proj_path"
            dotnet restore "$proj_path"
            dotnet build "$proj_path" --configuration ${{ env.BUILD_CONFIGURATION }} -p:Version=$NUGET_VERSION
            dotnet pack "$proj_path" --configuration ${{ env.BUILD_CONFIGURATION }} --no-build -p:PackageVersion=$NUGET_VERSION
          done

      - name: Push NuGet packages
        run: dotnet nuget push -k $NUGET_AUTH_TOKEN **/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY_NEOLUTION }}
